# Generated by Django 4.0.6 on 2022-07-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
